[default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.default]
optimize = true
optimizer_runs = 200

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.1.0" }
chainlink = { git = "https://github.com/smartcontractkit/chainlink", tag = "0.10.12" }
